<a href="https://colab.research.google.com/github/Parul-gargg/Pandas-Learning/blob/main/DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

Creating a DataFrame

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

Selection and Indexing of Columns

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a new column**

In [21]:
df["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

**Removing Columns**

In [23]:
df.drop(0,axis = 0)         #axis =0 works Horizontally, Axis=1 works Verically

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

In [26]:
df["Designation"] = ["Doctor","Eng.","Doctor","Eng."] # Ensure 'Designation' column exists
df.drop('Designation',axis = 1,inplace=True)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df.drop(['City','Salary'],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [28]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting** **Rows**

In [29]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
df.loc[[0,1]]     # loc means location it work on rows

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [31]:
df.iloc[3]      # index location

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting Subsets of Rows and Columns**

In [32]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

**Conditional Selection**

In [33]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#I only want to see those people whose age is above 30

In [34]:
df[df['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [36]:
#I only want poeple whose age is above 30 and their city must be paris

In [38]:
df[(df['Age'] > 30) & (df['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000